name: "Deploy para VPS"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "[1] Baixar o código"
        uses: actions/checkout@v4

      - name: "[2] Instalar Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: "[3] Instalar dependências do Angular"
        run: |
          npm ci

      - name: "[4] Build do projeto Angular"
        run: |
          rm -rf dist
          npm run build -- --configuration=production

      - name: "[5] Verificar arquivos gerados pelo Angular"
        run: |
          ls -lah dist/transportadora/browser

      - name: "[6] Configurar chave SSH para Hostinger"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.ftp_host }} >> ~/.ssh/known_hosts

      - name: "[7] Testar conexão SSH com debug"
        run: |
          ssh -o StrictHostKeyChecking=no -o LogLevel=DEBUG -i ~/.ssh/id_ed25519 ${{ secrets.ftp_user }}@${{ secrets.ftp_host }} "echo 'Conexão SSH bem-sucedida'"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "[8] Remover arquivos antigos antes do deploy"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /home/root/transportadora/dist/browser/*

      - name: "[9] Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/transportadora/browser/*"
          target: "/home/root/transportadora/dist/browser"

      - name: "[10] Verificar arquivos na VPS após deploy"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -lah /home/root/transportadora/dist/browser

      - name: "[11] Configurar permissões e reiniciar servidor"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R www-data:www-data /home/root/transportadora/dist/browser
            sudo systemctl restart nginx

      - name: "[12] Limpar cache do Nginx"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx